// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WoofWoofMaps.Models;

#nullable disable

namespace WoofWoofMaps.Migrations
{
    [DbContext(typeof(GeoTrackingContext))]
    partial class GeoTrackingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WoofWoofMaps.Models.GeoPoint", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.HasKey("Id");

                    b.ToTable("GeoPoints");
                });

            modelBuilder.Entity("WoofWoofMaps.Models.GeoRoute", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GeoRoutes");
                });

            modelBuilder.Entity("WoofWoofMaps.Models.GeoRoutePoint", b =>
                {
                    b.Property<long>("GeoPointId")
                        .HasColumnType("bigint");

                    b.Property<long>("GeoRouteId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("GeoPointId", "GeoRouteId");

                    b.HasIndex("GeoRouteId");

                    b.ToTable("GeoRoutePoints");
                });

            modelBuilder.Entity("WoofWoofMaps.Models.GeoRoutePoint", b =>
                {
                    b.HasOne("WoofWoofMaps.Models.GeoPoint", "GeoPoint")
                        .WithMany("GeoRoutePoints")
                        .HasForeignKey("GeoPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WoofWoofMaps.Models.GeoRoute", "GeoRoute")
                        .WithMany("GeoRoutePoints")
                        .HasForeignKey("GeoRouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GeoPoint");

                    b.Navigation("GeoRoute");
                });

            modelBuilder.Entity("WoofWoofMaps.Models.GeoPoint", b =>
                {
                    b.Navigation("GeoRoutePoints");
                });

            modelBuilder.Entity("WoofWoofMaps.Models.GeoRoute", b =>
                {
                    b.Navigation("GeoRoutePoints");
                });
#pragma warning restore 612, 618
        }
    }
}
